# services:
#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     environment: 
#          REDIS_HOST: redis://redis:6379

#   redis:
#     image: redis

version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Map the container port to the host
    depends_on:
      - redis # Ensure Redis starts before the backend
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./backend:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    container_name: redis-server
    ports:
      - "6379:6379" # Map Redis port

